core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
]


# use Django's local server to serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

# for patients
urlpatterns += [
    path('patients/', views.PatientsListView.as_view(), name='patients'),
    path('create-update-patient/',
         views.CreateUpdatePatientView.as_view(), name='create_update_patient'),
    path('search-patient/', views.SearchPatientView.as_view(), name='search_patient'),  # noqa
    path('delete-patient/', views.DeletePatientView.as_view(), name='delete_patient'),  # noqa
]

# for donors
urlpatterns += [
    path('donors/', views.DonorsListView.as_view(), name='donors'),
    path('create-update-donor/', views.CreateUpdateDonorView.as_view(),
         name='create_update_donor'),
    path('search-donor/', views.SearchDonorView.as_view(), name='search_donor'),
    path('delete-donor/', views.DeleteDonorView.as_view(), name='delete_donor'),
]

# for donations
urlpatterns += [
    path('donations/', views.DonationsListView.as_view(), name='donations'),
    path('create-update-donation/', views.CreateUpdateDonationView.as_view(), name='create_update_donation'),  # noqa
    path('search-donation/', views.SearchDonationView.as_view(), name='search_donation'),  # noqa
    path('delete-donation/', views.DeleteDonationView.as_view(), name='delete_donation'),  # noqa
]

# for blood requests
urlpatterns += [
    path('blood-requests/', views.BloodRequestsListView.as_view(), name='blood_requests'),  # noqa
    path('create-update-blood-request/', views.CreateUpdateBloodRequestView.as_view(), name='create_update_blood_request'),  # noqa
    path('blood-request-detail/', views.BloodRequestDetailsView.as_view(), name='blood_request_detail'),  # noqa
    path('search-blood-request/', views.SearchBloodRequestView.as_view(), name='search_blood_request'),  # noqa
    path('change-request-status/', views.ChangeRequestStatusView.as_view(), name='change_request_status'),  # noqa
    path('delete-blood-request/', views.DeleteBloodRequestView.as_view(), name='delete_blood_request'),  # noqa
]


# Users
urlpatterns += [
    path("users/", views.UsersListView.as_view(), name="users"),
    path("create-update-user/", views.CreateUpdateUserView.as_view(), name="create_update_user"),  # noqa
    path("search-user/", views.SearchUserView.as_view(), name="search_user"),  # noqa
    path("delete-user/", views.DeleteUserView.as_view(), name="delete_user"),  # noqa
    path("add-user-to-group/", views.AddUserToGroupsView.as_view(), name="add_user_to_group"),  # noqa
    path("add-perms-to-user/", views.AddPermsToUserView.as_view(), name="add_perms_to_user"),  # noqa
]

# Groups
urlpatterns += [
    path("groups/", views.GroupsListView.as_view(), name="groups"),
    path("create-update-group/", views.CreateUpdateGroupView.as_view(), name="create_update_group"),  # noqa
    path("search-group/", views.SearchGroupView.as_view(), name="search_group"),  # noqa
    path("delete-group/", views.DeleteGroupView.as_view(), name="delete_group"),  # noqa
    path('add-perms/', views.AddPermissionsToGroupView.as_view(), name='add_perms'),  # noqa
]


# profile urls
urlpatterns += [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update-profile/', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
]

core/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .manager import AccountManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    fullname = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    gender = models.CharField(max_length=15, blank=True, null=True)
    profile_image = models.ImageField(
        upload_to='profile_images', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    created_by_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_fullname(self):
        '''return the full name of the user'''
        return self.fullname if self.fullname else self.email

    objects = AccountManager()

    USERNAME_FIELD = 'email'

    def get_user_type_color(self) -> str:
        '''return the user type color'''
        if self.is_superuser:
            return 'danger'
        elif self.is_staff:
            return 'warning'
        else:
            return 'primary'

    def __str__(self):
        return self.get_fullname()

    class Meta:
        db_table = 'user'
        # custom permissions
        permissions = [
            ("view_profile", "Can view profile"),
            ("view_setting", "Can view setting"),
            ("change_profile", "Can update profile"),
            ("reset_password", "Can reset password"),
            ("add_user_to_group", "Can add user to group"),
            ("add_patient", "Can add patient"),
            ("change_patient", "Can update patient"),
            ("add_permission_to_user", "Can add permission to user"),
        ]

core/dashboard/models.py
from django.db import models
from accounts.models import User
from datetime import timedelta


class Donor(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField(default="default@gmail.com")
    blood_type = models.CharField(max_length=15)
    dob = models.DateField()
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    medical_condition = models.CharField(max_length=500)
    title = models.CharField(max_length=10)
    ocupation = models.CharField(max_length=100)
    id_type = models.CharField(max_length=20)
    id_number = models.CharField(max_length=30)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return self.fullname


class Donation(models.Model):
    '''Model to store donation details'''
    def generate_donation_id():
        # method to generate a custom ID for donation object
        from .models import Donation
        count = Donation.objects.count()
        return 'DON-#-000' + str(Donation.objects.count() + 1)

    donor = models.ForeignKey('Donor', on_delete=models.CASCADE, null=True)
    donation_id = models.CharField(default=generate_donation_id, max_length=20)  # noqa
    date_time_donated = models.DateTimeField()
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def expiration_date(self) -> timedelta:
        '''return the expiration date of the blood'''
        expiration_date = self.date_time_donated + timedelta(days=40)
        return expiration_date

    def blood_is_expired(self) -> bool:
        '''check if the blood has expired'''
        expiration_date = self.date_time_donated + timedelta(days=40)
        today = timezone.now()
        return today > expiration_date

    def blood_expires_in_a_week_or_less(self) -> bool:
        '''check if the blood will expire in a week or less'''
        expiration_date = self.date_time_donated + timedelta(days=40)
        today = timezone.now()
        time_until_expiration = expiration_date - today
        return time_until_expiration <= timedelta(days=7)

    def __str__(self) -> str:
        return self.donation_id + ' - ' + self.donor.fullname if self.donor else 'No Donor'


class PatientProfile(models.Model):
    '''Model to store patient profile - A patient is a user'''
    blood_type = models.CharField(max_length=15)
    dob = models.DateField()
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.user.fullname if self.user else 'No User'


class BloodRequest(models.Model):
    '''Model to blood requests made by patients'''

    def generate_request_id():
        # method to generate a custom ID for blood request object
        count = BloodRequest.objects.count()
        return 'BREQ-#-000' + str(BloodRequest.objects.count() + 1)
    blood_request_id = models.CharField(default=generate_request_id, max_length=20)  # noqa
    patient_profile = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, null=True)  # noqa
    request_form = models.ImageField(upload_to='request_forms', null=True, blank=True)  # noqa
    quantity = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.CharField(max_length=20, default='PENDING')
    date_requested = models.DateTimeField(auto_now_add=True)
    date_approve_rejected = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_status_color(self) -> str:
        if self.status.upper == 'PENDING':
            return 'green'
        elif self.status.upper == 'APPROVED':
            return 'blue'
        else:
            return 'red'

    def __str__(self) -> str:
        return self.blood_request_id + ' - ' + self.patient_profile.user.fullname

    class Meta:
        # custom permissions
        permissions = [
            ("change_request_status", "Can change blood request status"),
        ]

core/dashboard/forms.py
from django import forms
from accounts.models import User
from dashboard.models import Donor, PatientProfile, Donation, BloodRequest


class UserForm(forms.ModelForm):
    '''Form for creating a new user'''
    class Meta:
        model = User
        fields = ['email', 'fullname', 'phone', 'gender', 'profile_image', ]


class PatientProfileForm(forms.ModelForm):
    '''Form for creating a new user profile'''
    class Meta:
        model = PatientProfile
        exclude = ['created_at', 'user', ]


class DonorForm(forms.ModelForm):
    '''Form for creating a new donor'''
    class Meta:
        model = Donor
        exclude = ['created_at', 'created_by', ]


class DonationForm(forms.ModelForm):
    '''Form for creating a new donation'''
    class Meta:
        model = Donation
        fields = ['date_time_donated', 'quantity', ]


class BloodRequestForm(forms.ModelForm):
    '''Form for creating a new blood request'''
    class Meta:
        model = BloodRequest
        fields = ['quantity', ]

core/dashboard/views/dashboard.py
import datetime
from datetime import timedelta, timezone
from django.utils import timezone as tz
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View
from dashboard.models import Donation, Donor, PatientProfile, BloodRequest
from django.db.models import Count, Sum, F, FloatField
from core.utils.decorators import MustLogin
from django.utils.decorators import method_decorator


class DashboardView(View):
    '''CBV for rendering the dashboard page'''

    template = 'dashboard/dashboard.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        # expired bloods
        expired_blood_count = Donation.objects.filter(
            date_time_donated__lte=tz.now()-timedelta(days=40)).count()
        # bloods expiring in a week or less
        expiring_blood_count = Donation.objects.filter(date_time_donated__gt=tz.now(
        )-timedelta(days=40), date_time_donated__lte=tz.now()+timedelta(days=7)).count()
        # messages
        message = f'{expired_blood_count} quantum of blood has expired | {expiring_blood_count} quantum of blood will expire in a week or less'  # noqa
        blood_types = Donation.objects.values_list('donor__blood_type', flat=True).distinct()  # noqa
        blood_type_counts = Donation.objects.values('donor__blood_type').annotate(count=Count('donor__blood_type'))  # noqa

        # get the total quantity of each blood type in the Donation model
        blood_type_totals = Donation.objects.values(
            'donor__blood_type').annotate(total_quantity=Sum('quantity'))

        # get the total quantity of each blood type requested in the BloodRequest model
        blood_type_requests = BloodRequest.objects.filter(status__in=['PENDING', 'REJECTED']).values(
            'patient_profile__blood_type').annotate(requested_quantity=Sum('quantity'))

        # combine the above queries to get the final result
        blood_type_info = []
        for blood_type in set(blood_type_totals.values_list('donor__blood_type', flat=True)):

            total_quantity = blood_type_totals.filter(
                donor__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            approve_requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type, status='APPROVED').aggregate(Sum('quantity'))['quantity__sum']

            available_quantity = float(
                total_quantity) - float(approve_requested_quantity or 0)

            blood_type_info.append({
                'blood_type': blood_type,
                'total_quantity': str(total_quantity or 0),
                'requested_quantity': str(requested_quantity or 0),
                'approve_requested_quantity': str(approve_requested_quantity or 0),
                'available_quantity': str(available_quantity)
            })

        # only display messages blood expiration message to staff and superusers
        if request.user.is_staff or request.user.is_superuser:
            messages.info(request, message)
        request_history = BloodRequest.objects.filter(
            patient_profile__user=request.user).order_by('-blood_request_id')

        context = {
            'blood_types': blood_types,
            'blood_type_counts': blood_type_counts,
            'blood_type_info': blood_type_info,
            'request_history': request_history,
        }

        return render(request, self.template, context)

core/dashboard/views/user_profile.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View

from core.utils.decorators import MustLogin


class ProfileView(PermissionRequiredMixin, View):
    '''CBV for profile page'''
    permission_required = [
        'accounts.view_profile',
    ]

    template = 'dashboard/profile.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        context = {
        }
        return render(request, self.template, context)


class ProfileUpdateView(PermissionRequiredMixin, View):
    '''CBV for profile update page'''
    permission_required = [
        'accounts.view_profile',
        'accounts.change_profile',
    ]

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:profile')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        user = request.user
        user.fullname = request.POST.get('fullname')
        user.phone = request.POST.get('phone')
        user.gender = request.POST.get('gender')
        if request.FILES.get('profile_image'):
            try:
                user.profile_image = request.FILES.get('profile_image')
            except:
                print('Error while uploading profile image')
            else:
                print('Profile image uploaded successfully')
        user.save()
        messages.success(request, 'Profile Updated successfully')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class PasswordResetView(PermissionRequiredMixin, View):
    '''CBV for password reset page'''
    permission_required = [
        'accounts.view_profile',
        'accounts.change_profile',
        'accounts.reset_password',
    ]

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:profile')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        password1 = request.POST.get('new_password')
        password2 = request.POST.get('confirm_password')
        if password1 == password2:
            user = request.user
            user.set_password(password1)
            user.save()
            messages.success(request, 'Password Changed successfully')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.info(request, 'Password does not match')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/dashboard/templates/dashboard/blood_requests.html
{% extends "base/base.html" %}

{% block title %} Blood Requests {% endblock %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item"><a href="#">Blood Requests</a></li>
                <li class="breadcrumb-item active" aria-current="page">All Blood Requests</li>
            </ol>
        </nav>
        <h2 class="h4">All Blood Requests</h2>
        <p class="mb-0">A list of all Blood Requests...</p>
    </div>

    {% if perms.dashboard.add_bloodrequest %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group ms-2 ms-lg-3">
            <a href="{% url 'dashboard:create_update_blood_request' %}" class="btn btn-sm btn-outline-gray-600">
                <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M12 6v6m0 0v6m0-6h6m-6 0H6">
                    </path>
                </svg>
                New Blood Request
            </a>
        </div>
    </div>
    {% endif %}
</div>

<div class="table-settings mb-4">
    <div class="row align-items-center justify-content-between">

        <div class="col col-md-6 col-lg-3 col-xl-4">
            <div class="input-group me-2 me-lg-3 fmxw-400">
                <form action="{% url 'dashboard:search_blood_request' %}" method="GET">
                    <div class="row">
                        <div class="col-9 mx-0" style="padding-right: 0;">
                            <input type="text" class="form-control" name="q" placeholder="request id, qty, etc.">
                        </div>
                        <div class="col-3 mx-0" style="padding-left: 0;">
                            <span><button class="btn btn-sm btn-primary">Search</button></span>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<div class="card card-body border-0 shadow table-wrapper table-responsive">
    <table class="table table-hover">
        <thead class="table-dark">
            <tr>
                <th class="border-gray-200">#</th>
                <th class="border-gray-200">Request ID</th>
                <th class="border-gray-200">Patient</th>
                <th class="border-gray-200">Quantity</th>
                <th class="border-gray-200">Status</th>
                <th class="border-gray-200">Date Requested</th>
                <th class="border-gray-200">Action</th>
            </tr>
        </thead>
        <tbody>
            <!-- Item -->
            {% if blood_requests %}
            {% for blood_request in blood_requests %}
            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td>
                    <a href="#" class="fw-bold">
                        {{blood_request.blood_request_id}}
                    </a>
                </td>
                <td>
                    <span class="fw-normal">{{blood_request.patient_profile.user.fullname}}</span>
                </td>
                <td><span class="fw-bold">{{blood_request.quantity}}</span></td>
                <td><span class="badge fw-bold"
                        style="background-color: {{blood_request.get_status_color}};">{{blood_request.status}}</span>
                </td>
                <td><span class="fw-normal">{{blood_request.date_requested}}</span></td>
                <td>
                    <div class="btn-group">

                        <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-0"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="icon icon-sm">
                                <span class="fas fa-ellipsis-h icon-dark"></span>
                            </span>
                        </button>
                        <div class="dropdown-menu py-0">

                            {% if perms.dashboard.change_bloodrequest %}
                            <a class="dropdown-item"
                                href="{% url 'dashboard:create_update_blood_request' %}?request_id={{blood_request.id}}"><span
                                    class="fas fa-edit me-2"></span>Edit</a>
                            {% endif %}

                            {% if perms.dashboard.view_bloodrequest %}
                            <a class="dropdown-item"
                                href="{% url 'dashboard:blood_request_detail' %}?request_id={{blood_request.id}}"><span
                                    class="fas fa-eye me-2"></span>View</a>
                            {% endif %}

                            {% if perms.dashboard.delete_bloodrequest %}
                            <form action="{% url 'dashboard:delete_blood_request' %}" method="POST"
                                style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="blood_request_id" value="{{blood_request.id}}">
                                <button type="submit" class="dropdown-item text-danger rounded-bottom"><span
                                        class="fas fa-trash-alt me-2"></span>Delete</button>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="7">
                    <p class="text-center">No Blood Request Added Yet</p>
                </td>
            </tr>
            {% endif %}

        </tbody>
    </table>
    <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
        <nav aria-label="Page navigation example">
            <ul class="pagination mb-0">
                <li class="page-item">
                    <a class="page-link" href="#">Previous</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">4</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">5</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
        <div class="fw-normal small mt-4 mt-lg-0">Showing <b>{{total_blood_requests}}</b> out of
            <b>{{total_blood_requests}}</b>
            entries</div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}