core/accounts/urls.py
from django.urls import path

from .views import LoginView, LogoutView, RegisterView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
]


# use Django's local server to serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

# for patients
urlpatterns += [
    path('patients/', views.PatientsListView.as_view(), name='patients'),
    path('create-update-patient/',
         views.CreateUpdatePatientView.as_view(), name='create_update_patient'),
    path('search-patient/', views.SearchPatientView.as_view(), name='search_patient'),  # noqa
    path('delete-patient/', views.DeletePatientView.as_view(), name='delete_patient'),  # noqa
]

# for donors
urlpatterns += [
    path('donors/', views.DonorsListView.as_view(), name='donors'),
    path('create-update-donor/', views.CreateUpdateDonorView.as_view(),
         name='create_update_donor'),
    path('search-donor/', views.SearchDonorView.as_view(), name='search_donor'),
    path('delete-donor/', views.DeleteDonorView.as_view(), name='delete_donor'),
]

# for donations
urlpatterns += [
    path('donations/', views.DonationsListView.as_view(), name='donations'),
    path('create-update-donation/', views.CreateUpdateDonationView.as_view(), name='create_update_donation'),  # noqa
    path('search-donation/', views.SearchDonationView.as_view(), name='search_donation'),  # noqa
    path('delete-donation/', views.DeleteDonationView.as_view(), name='delete_donation'),  # noqa
]

# for blood requests
urlpatterns += [
    path('blood-requests/', views.BloodRequestsListView.as_view(), name='blood_requests'),  # noqa
    path('create-update-blood-request/', views.CreateUpdateBloodRequestView.as_view(), name='create_update_blood_request'),  # noqa
    path('blood-request-detail/', views.BloodRequestDetailsView.as_view(), name='blood_request_detail'),  # noqa
    path('search-blood-request/', views.SearchBloodRequestView.as_view(), name='search_blood_request'),  # noqa
    path('change-request-status/', views.ChangeRequestStatusView.as_view(), name='change_request_status'),  # noqa
    path('delete-blood-request/', views.DeleteBloodRequestView.as_view(), name='delete_blood_request'),  # noqa
]


# Users
urlpatterns += [
    path("users/", views.UsersListView.as_view(), name="users"),
    path("create-update-user/", views.CreateUpdateUserView.as_view(), name="create_update_user"),  # noqa
    path("search-user/", views.SearchUserView.as_view(), name="search_user"),  # noqa
    path("delete-user/", views.DeleteUserView.as_view(), name="delete_user"),  # noqa
    path("add-user-to-group/", views.AddUserToGroupsView.as_view(), name="add_user_to_group"),  # noqa
    path("add-perms-to-user/", views.AddPermsToUserView.as_view(), name="add_perms_to_user"),  # noqa
]

# Groups
urlpatterns += [
    path("groups/", views.GroupsListView.as_view(), name="groups"),
    path("create-update-group/", views.CreateUpdateGroupView.as_view(), name="create_update_group"),  # noqa
    path("search-group/", views.SearchGroupView.as_view(), name="search_group"),  # noqa
    path("delete-group/", views.DeleteGroupView.as_view(), name="delete_group"),  # noqa
    path('add-perms/', views.AddPermissionsToGroupView.as_view(), name='add_perms'),  # noqa
]


# profile urls
urlpatterns += [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update-profile/', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
]

core/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .manager import AccountManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    fullname = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    gender = models.CharField(max_length=15, blank=True, null=True)
    profile_image = models.ImageField(
        upload_to='profile_images', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    created_by_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_fullname(self):
        '''return the full name of the user'''
        return self.fullname if self.fullname else self.email

    objects = AccountManager()

    USERNAME_FIELD = 'email'

    def get_user_type_color(self) -> str:
        '''return the user type color'''
        if self.is_superuser:
            return 'danger'
        elif self.is_staff:
            return 'warning'
        else:
            return 'primary'

    def __str__(self):
        return self.get_fullname()

    class Meta:
        db_table = 'user'
        # custom permissions
        permissions = [
            ("view_profile", "Can view profile"),
            ("view_setting", "Can view setting"),
            ("change_profile", "Can update profile"),
            ("reset_password", "Can reset password"),
            ("add_user_to_group", "Can add user to group"),
            ("add_patient", "Can add patient"),
            ("change_patient", "Can update patient"),
            ("add_permission_to_user", "Can add permission to user"),
        ]

core/dashboard/models.py
from django.db import models
from accounts.models import User
from datetime import timedelta


class Donor(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField(default="default@gmail.com")
    blood_type = models.CharField(max_length=15)
    dob = models.DateField()
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    medical_condition = models.CharField(max_length=500)
    title = models.CharField(max_length=10)
    ocupation = models.CharField(max_length=100)
    id_type = models.CharField(max_length=20)
    id_number = models.CharField(max_length=30)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return self.fullname


class Donation(models.Model):
    '''Model to store donation details'''
    def generate_donation_id():
        # method to generate a custom ID for donation object
        from .models import Donation
        count = Donation.objects.count()
        return 'DON-#-000' + str(Donation.objects.count() + 1)

    donor = models.ForeignKey('Donor', on_delete=models.CASCADE, null=True)
    donation_id = models.CharField(default=generate_donation_id, max_length=20)  # noqa
    date_time_donated = models.DateTimeField()
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def expiration_date(self) -> timedelta:
        '''return the expiration date of the blood'''
        expiration_date = self.date_time_donated + timedelta(days=40)
        return expiration_date

    def blood_is_expired(self) -> bool:
        '''check if the blood has expired'''
        expiration_date = self.date_time_donated + timedelta(days=40)
        today = timezone.now()
        return today > expiration_date

    def blood_expires_in_a_week_or_less(self) -> bool:
        '''check if the blood will expire in a week or less'''
        expiration_date = self.date_time_donated + timedelta(days=40)
        today = timezone.now()
        time_until_expiration = expiration_date - today
        return time_until_expiration <= timedelta(days=7)

    def __str__(self) -> str:
        return self.donation_id + ' - ' + self.donor.fullname if self.donor else 'No Donor'


class PatientProfile(models.Model):
    '''Model to store patient profile - A patient is a user'''
    blood_type = models.CharField(max_length=15)
    dob = models.DateField()
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.user.fullname if self.user else 'No User'


class BloodRequest(models.Model):
    '''Model to blood requests made by patients'''

    def generate_request_id():
        # method to generate a custom ID for blood request object
        count = BloodRequest.objects.count()
        return 'BREQ-#-000' + str(BloodRequest.objects.count() + 1)
    blood_request_id = models.CharField(default=generate_request_id, max_length=20)  # noqa
    patient_profile = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, null=True)  # noqa
    request_form = models.ImageField(upload_to='request_forms', null=True, blank=True)  # noqa
    quantity = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.CharField(max_length=20, default='PENDING')
    date_requested = models.DateTimeField(auto_now_add=True)
    date_approve_rejected = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_status_color(self) -> str:
        if self.status.upper == 'PENDING':
            return 'green'
        elif self.status.upper == 'APPROVED':
            return 'blue'
        else:
            return 'red'

    def __str__(self) -> str:
        return self.blood_request_id + ' - ' + self.patient_profile.user.fullname

    class Meta:
        # custom permissions
        permissions = [
            ("change_request_status", "Can change blood request status"),
        ]

core/dashboard/views/dashboard.py
import datetime
from datetime import timedelta, timezone
from django.utils import timezone as tz
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View
from dashboard.models import Donation, Donor, PatientProfile, BloodRequest
from django.db.models import Count, Sum, F, FloatField
from core.utils.decorators import MustLogin
from django.utils.decorators import method_decorator


class DashboardView(View):
    '''CBV for rendering the dashboard page'''

    template = 'dashboard/dashboard.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        # expired bloods
        expired_blood_count = Donation.objects.filter(
            date_time_donated__lte=tz.now()-timedelta(days=40)).count()
        # bloods expiring in a week or less
        expiring_blood_count = Donation.objects.filter(date_time_donated__gt=tz.now(
        )-timedelta(days=40), date_time_donated__lte=tz.now()+timedelta(days=7)).count()
        # messages
        message = f'{expired_blood_count} quantum of blood has expired | {expiring_blood_count} quantum of blood will expire in a week or less'  # noqa
        blood_types = Donation.objects.values_list('donor__blood_type', flat=True).distinct()  # noqa
        blood_type_counts = Donation.objects.values('donor__blood_type').annotate(count=Count('donor__blood_type'))  # noqa

        # get the total quantity of each blood type in the Donation model
        blood_type_totals = Donation.objects.values(
            'donor__blood_type').annotate(total_quantity=Sum('quantity'))

        # get the total quantity of each blood type requested in the BloodRequest model
        blood_type_requests = BloodRequest.objects.filter(status__in=['PENDING', 'REJECTED']).values(
            'patient_profile__blood_type').annotate(requested_quantity=Sum('quantity'))

        # combine the above queries to get the final result
        blood_type_info = []
        for blood_type in set(blood_type_totals.values_list('donor__blood_type', flat=True)):

            total_quantity = blood_type_totals.filter(
                donor__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            approve_requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type, status='APPROVED').aggregate(Sum('quantity'))['quantity__sum']

            available_quantity = float(
                total_quantity) - float(approve_requested_quantity or 0)

            blood_type_info.append({
                'blood_type': blood_type,
                'total_quantity': str(total_quantity or 0),
                'requested_quantity': str(requested_quantity or 0),
                'approve_requested_quantity': str(approve_requested_quantity or 0),
                'available_quantity': str(available_quantity)
            })

        # only display messages blood expiration message to staff and superusers
        if request.user.is_staff or request.user.is_superuser:
            messages.info(request, message)
        request_history = BloodRequest.objects.filter(
            patient_profile__user=request.user).order_by('-blood_request_id')

        context = {
            'blood_types': blood_types,
            'blood_type_counts': blood_type_counts,
            'blood_type_info': blood_type_info,
            'request_history': request_history,
        }

        return render(request, self.template, context)

core/dashboard/views/user_profile.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View

from core.utils.decorators import MustLogin


class ProfileView(PermissionRequiredMixin, View):
    '''CBV for profile page'''
    permission_required = [
        'accounts.view_profile',
    ]

    template = 'dashboard/profile.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        context = {
        }
        return render(request, self.template, context)


class ProfileUpdateView(PermissionRequiredMixin, View):
    '''CBV for profile update page'''
    permission_required = [
        'accounts.view_profile',
        'accounts.change_profile',
    ]

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:profile')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        user = request.user
        user.fullname = request.POST.get('fullname')
        user.phone = request.POST.get('phone')
        user.gender = request.POST.get('gender')
        if request.FILES.get('profile_image'):
            try:
                user.profile_image = request.FILES.get('profile_image')
            except:
                print('Error while uploading profile image')
            else:
                print('Profile image uploaded successfully')
        user.save()
        messages.success(request, 'Profile Updated successfully')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class PasswordResetView(PermissionRequiredMixin, View):
    '''CBV for password reset page'''
    permission_required = [
        'accounts.view_profile',
        'accounts.change_profile',
        'accounts.reset_password',
    ]

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:profile')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        password1 = request.POST.get('new_password')
        password2 = request.POST.get('confirm_password')
        if password1 == password2:
            user = request.user
            user.set_password(password1)
            user.save()
            messages.success(request, 'Password Changed successfully')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.info(request, 'Password does not match')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/dashboard/templates/includes/compliance_filter.html
<div class="row">
    <div class="col-6">
        <div class="py-4">
            <!-- form for filtering queryset -->
            <form action="" method="GET">
                <div class="row">
                    <div class="col-6 mx-0">
                        <div class="input-group">
                            <!-- <label for="">Parameter</label> -->
                            <select name="week_id" id="week_id" class="form-select">
                                {% for week in weeks %}
                                <option value="{{ week.id }}" {% if week.id == current_week.id %} selected {% endif %}>
                                    {{ week.title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-6 mx-0">
                        <button class="btn btn-sm btn-primary">Show Report</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- this button opens a modal -->
    <div class="col-6 my-4 text-right">
        <button type="button" class="btn btn-sm btn-primary text-white" data-bs-toggle="modal"
            data-bs-target="#modal-compliance"><span class="bi bi-plus">
                New Week Report</span></button>
    </div>

</div>

core/dashboard/templates/includes/navigation.html
{% load static %}
<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
  <div class="container-fluid px-0">
    <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
      <div class="d-flex align-items-center text-primary">
        <b>Hi there, {{request.user.get_fullname}}!</b>
      </div>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center">
        <li class="nav-item dropdown ms-lg-3">
          <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            <div class="media d-flex align-items-center">
              <img class="avatar rounded-circle"
                src="{% if request.user.profile_image %} {{ request.user.profile_image.url }} {% else %} {% static '/assets/img/team/profile-picture-3.jpg' %} {% endif %} "
                class="avatar-xl rounded-circle mx-auto mt-n7 mb-4" alt="Neil Portrait">
              <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                <span class="mb-0 font-small fw-bold text-gray-900">
                  {% if request.user.get_fullname %}
                  <strong>{{ request.user.get_fullname }}</strong>
                  {% else %}
                  <strong>Guest</strong>
                  {% endif %}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
            <a class="dropdown-item d-flex align-items-center" href="{% url 'dashboard:profile' %}">
              <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z"
                  clip-rule="evenodd"></path>
              </svg>
              Profile
            </a>
            <div role="separator" class="dropdown-divider my-1"></div>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:logout' %}">
              <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
              </svg>
              Logout
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- display django messages -->
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</div>

core/dashboard/templates/includes/sidebar.html
        {% load static %}
        <nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
          <a class="navbar-brand me-lg-5" href="/">
            <img class="navbar-brand-dark" src="{% static '/assets/img/brand/logo-w.png' %}" alt="OBBS logo" /> <img
              class="navbar-brand-light" src="{% static '/assets/img/brand/logo-w.png' %}" alt="OBBS logo" />
          </a>
          <div class="d-flex align-items-center">
            <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
              data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </nav>

        <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
          <div class="sidebar-inner px-4 pt-3">
            <div
              class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
              <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                  <img src="{% static '/assets/img/team/profile-picture-3.jpg' %}"
                    class="card-img-top rounded-circle border-white" alt="Bonnie Green">
                </div>
                <div class="d-block">
                  <h2 class="h5 mb-3">Hi, {{request.user.email}}</h2>
                  <a href="" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                    <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                      xmlns="http://www.w3.org/2000/svg">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                      </path>
                    </svg>
                    Sign Out
                  </a>
                </div>
              </div>
              <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu"
                  aria-controls="sidebarMenu" aria-expanded="true" aria-label="Toggle navigation">
                  <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                      d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                      clip-rule="evenodd"></path>
                  </svg>
                </a>
              </div>
            </div>
            <ul class="nav flex-column pt-3 pt-md-0">
              <li class="nav-item">
                <a href="javascript:void()" class="nav-link d-flex align-items-center">
                  <img src="{% static '/assets/img/brand/logo-w.png' %}" alt="OBBS logo" />
                </a>
              </li>
              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:dashboard' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="bi bi-speedometer2"></i>
                  </span>
                  <span class="sidebar-text">Dashboard</span>
                </a>
              </li>

              {% if perms.dashboard.view_patientprofile %}
              <li class="nav-item {% if 'donations' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:patients' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="bi bi-people"></i>
                  </span>
                  <span class="sidebar-text">Patients</span>
                </a>
              </li>
              {% endif %}

              {% if perms.dashboard.view_donor %}
              <li class="nav-item {% if 'donations' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:donors' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="bi bi-person-check"></i>
                  </span>
                  <span class="sidebar-text">Donors</span>
                </a>
              </li>
              {% endif %}

              {% if perms.dashboard.view_donation %}
              <li class="nav-item {% if 'donations' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:donations' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <!-- <i class="bi bi-magic"></i> -->
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                      class="bi bi-hearts" viewBox="0 0 16 16">
                      <path fill-rule="evenodd"
                        d="M4.931.481c1.627-1.671 5.692 1.254 0 5.015-5.692-3.76-1.626-6.686 0-5.015Zm6.84 1.794c1.084-1.114 3.795.836 0 3.343-3.795-2.507-1.084-4.457 0-3.343ZM7.84 7.642c2.71-2.786 9.486 2.09 0 8.358-9.487-6.268-2.71-11.144 0-8.358Z" />
                    </svg>
                  </span>
                  <span class="sidebar-text">Donations</span>
                </a>
              </li>
              {% endif %}

              {% if perms.dashboard.view_bloodrequest %}
              <li class="nav-item {% if 'doctrines' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:blood_requests' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="bi bi-heart-half"></i>
                  </span>
                  <span class="sidebar-text">Blood Requests</span>
                </a>
              </li>
              {% endif %}

              {% if perms.dashboard.view_setting %}
              <li class="nav-item {% if 'users-' in segment %} active {% endif %}">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center"
                  data-bs-toggle="collapse" data-bs-target="#submenu-setup">
                  <span>
                    <span class="sidebar-icon">
                      <i class="bi bi-gear"></i>
                    </span>
                    <span class="sidebar-text">Settings</span>
                  </span>
                  <span class="link-arrow">
                    <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                    </svg>
                  </span>
                </span>

                {% if perms.accounts.view_user %}
                <div class="multi-level collapse {% if 'setup-' in segment %} show {% endif %}" role="list"
                  id="submenu-setup" aria-expanded="false">
                  <ul class="flex-column nav">
                    <li class="nav-item {% if 'setup-buttons' in segment %} active {% endif %}">
                      <a class="nav-link" href="{% url 'dashboard:users' %}">
                        <span class="sidebar-text">Users</span>
                      </a>
                    </li>
                  </ul>
                </div>
                {% endif %}

                {% if perms.accounts.view_group or perms.dashboard.view_group %}
                <div class="multi-level collapse {% if 'setup-' in segment %} show {% endif %}" role="list"
                  id="submenu-setup" aria-expanded="false">
                  <ul class="flex-column nav">
                    <li class="nav-item {% if 'setup-buttons' in segment %} active {% endif %}">
                      <a class="nav-link" href="{% url 'dashboard:groups' %}">
                        <span class="sidebar-text">Groups</span>
                      </a>
                    </li>
                  </ul>
                </div>
                {% endif %}
              </li>
              {% endif %}

              <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>

              {% if perms.accounts.view_profile %}
              <li class="nav-item {% if 'profile' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:profile' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="bi bi-gear"></i>
                  </span>
                  <span class="sidebar-text">Profile</span>
                </a>
              </li>
              {% endif %}

              <li class="nav-item">
                <a href="{% url 'accounts:logout' %}" class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <i class="bi bi-power"></i>
                  </span>
                  <span class="sidebar-text">Logout</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>