core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
]


# use Django's local server to serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

# for patients
urlpatterns += [
    path('patients/', views.PatientsListView.as_view(), name='patients'),
    path('create-update-patient/',
         views.CreateUpdatePatientView.as_view(), name='create_update_patient'),
    path('search-patient/', views.SearchPatientView.as_view(), name='search_patient'),  # noqa
    path('delete-patient/', views.DeletePatientView.as_view(), name='delete_patient'),  # noqa
]

# for donors
urlpatterns += [
    path('donors/', views.DonorsListView.as_view(), name='donors'),
    path('create-update-donor/', views.CreateUpdateDonorView.as_view(),
         name='create_update_donor'),
    path('search-donor/', views.SearchDonorView.as_view(), name='search_donor'),
    path('delete-donor/', views.DeleteDonorView.as_view(), name='delete_donor'),
]

# for donations
urlpatterns += [
    path('donations/', views.DonationsListView.as_view(), name='donations'),
    path('create-update-donation/', views.CreateUpdateDonationView.as_view(), name='create_update_donation'),  # noqa
    path('search-donation/', views.SearchDonationView.as_view(), name='search_donation'),  # noqa
    path('delete-donation/', views.DeleteDonationView.as_view(), name='delete_donation'),  # noqa
]

# for blood requests
urlpatterns += [
    path('blood-requests/', views.BloodRequestsListView.as_view(), name='blood_requests'),  # noqa
    path('create-update-blood-request/', views.CreateUpdateBloodRequestView.as_view(), name='create_update_blood_request'),  # noqa
    path('blood-request-detail/', views.BloodRequestDetailsView.as_view(), name='blood_request_detail'),  # noqa
    path('search-blood-request/', views.SearchBloodRequestView.as_view(), name='search_blood_request'),  # noqa
    path('change-request-status/', views.ChangeRequestStatusView.as_view(), name='change_request_status'),  # noqa
    path('delete-blood-request/', views.DeleteBloodRequestView.as_view(), name='delete_blood_request'),  # noqa
]


# Users
urlpatterns += [
    path("users/", views.UsersListView.as_view(), name="users"),
    path("create-update-user/", views.CreateUpdateUserView.as_view(), name="create_update_user"),  # noqa
    path("search-user/", views.SearchUserView.as_view(), name="search_user"),  # noqa
    path("delete-user/", views.DeleteUserView.as_view(), name="delete_user"),  # noqa
    path("add-user-to-group/", views.AddUserToGroupsView.as_view(), name="add_user_to_group"),  # noqa
    path("add-perms-to-user/", views.AddPermsToUserView.as_view(), name="add_perms_to_user"),  # noqa
]

# Groups
urlpatterns += [
    path("groups/", views.GroupsListView.as_view(), name="groups"),
    path("create-update-group/", views.CreateUpdateGroupView.as_view(), name="create_update_group"),  # noqa
    path("search-group/", views.SearchGroupView.as_view(), name="search_group"),  # noqa
    path("delete-group/", views.DeleteGroupView.as_view(), name="delete_group"),  # noqa
    path('add-perms/', views.AddPermissionsToGroupView.as_view(), name='add_perms'),  # noqa
]


# profile urls
urlpatterns += [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update-profile/', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
]

core/dashboard/forms.py
from django import forms
from accounts.models import User
from dashboard.models import Donor, PatientProfile, Donation, BloodRequest


class UserForm(forms.ModelForm):
    '''Form for creating a new user'''
    class Meta:
        model = User
        fields = ['email', 'fullname', 'phone', 'gender', 'profile_image', ]


class PatientProfileForm(forms.ModelForm):
    '''Form for creating a new user profile'''
    class Meta:
        model = PatientProfile
        exclude = ['created_at', 'user', ]


class DonorForm(forms.ModelForm):
    '''Form for creating a new donor'''
    class Meta:
        model = Donor
        exclude = ['created_at', 'created_by', ]


class DonationForm(forms.ModelForm):
    '''Form for creating a new donation'''
    class Meta:
        model = Donation
        fields = ['date_time_donated', 'quantity', ]


class BloodRequestForm(forms.ModelForm):
    '''Form for creating a new blood request'''
    class Meta:
        model = BloodRequest
        fields = ['quantity', ]

core/dashboard/views/dashboard.py
import datetime
from datetime import timedelta, timezone
from django.utils import timezone as tz
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View
from dashboard.models import Donation, Donor, PatientProfile, BloodRequest
from django.db.models import Count, Sum, F, FloatField
from core.utils.decorators import MustLogin
from django.utils.decorators import method_decorator


class DashboardView(View):
    '''CBV for rendering the dashboard page'''

    template = 'dashboard/dashboard.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        # expired bloods
        expired_blood_count = Donation.objects.filter(
            date_time_donated__lte=tz.now()-timedelta(days=40)).count()
        # bloods expiring in a week or less
        expiring_blood_count = Donation.objects.filter(date_time_donated__gt=tz.now(
        )-timedelta(days=40), date_time_donated__lte=tz.now()+timedelta(days=7)).count()
        # messages
        message = f'{expired_blood_count} quantum of blood has expired | {expiring_blood_count} quantum of blood will expire in a week or less'  # noqa
        blood_types = Donation.objects.values_list('donor__blood_type', flat=True).distinct()  # noqa
        blood_type_counts = Donation.objects.values('donor__blood_type').annotate(count=Count('donor__blood_type'))  # noqa

        # get the total quantity of each blood type in the Donation model
        blood_type_totals = Donation.objects.values(
            'donor__blood_type').annotate(total_quantity=Sum('quantity'))

        # get the total quantity of each blood type requested in the BloodRequest model
        blood_type_requests = BloodRequest.objects.filter(status__in=['PENDING', 'REJECTED']).values(
            'patient_profile__blood_type').annotate(requested_quantity=Sum('quantity'))

        # combine the above queries to get the final result
        blood_type_info = []
        for blood_type in set(blood_type_totals.values_list('donor__blood_type', flat=True)):

            total_quantity = blood_type_totals.filter(
                donor__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            approve_requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type, status='APPROVED').aggregate(Sum('quantity'))['quantity__sum']

            available_quantity = float(
                total_quantity) - float(approve_requested_quantity or 0)

            blood_type_info.append({
                'blood_type': blood_type,
                'total_quantity': str(total_quantity or 0),
                'requested_quantity': str(requested_quantity or 0),
                'approve_requested_quantity': str(approve_requested_quantity or 0),
                'available_quantity': str(available_quantity)
            })

        # only display messages blood expiration message to staff and superusers
        if request.user.is_staff or request.user.is_superuser:
            messages.info(request, message)
        request_history = BloodRequest.objects.filter(
            patient_profile__user=request.user).order_by('-blood_request_id')

        context = {
            'blood_types': blood_types,
            'blood_type_counts': blood_type_counts,
            'blood_type_info': blood_type_info,
            'request_history': request_history,
        }

        return render(request, self.template, context)

core/dashboard/views/donations.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from core.utils.decorators import MustLogin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View
from dashboard.models import Donation, Donor
from dashboard.forms import DonationForm


class DonationsListView(PermissionRequiredMixin, View):
    '''Class for showing the list of Donations'''
    permission_required = ['dashboard.view_donation']

    template = 'dashboard/donations.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        donations = Donation.objects.all().order_by('-created_at')
        context = {
            'donations': donations,
        }
        return render(request, self.template, context)


class CreateUpdateDonationView(PermissionRequiredMixin, View):
    '''Class for creating and updating donations'''
    permission_required = ['dashboard.add_donation']
    template = 'dashboard/form-renderers/create_update_donation.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        donation_id = request.GET.get('donation_id') or None
        donation = Donation.objects.filter(id=donation_id).first()
        donors = Donor.objects.all().order_by('-id')
        context = {
            'donation': donation,
            'donors': donors,
        }
        return render(request, self.template, context)

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donation_id = request.POST.get('donation_id') or None
        donation = Donation.objects.filter(id=donation_id).first()
        donor_id = request.POST.get('donor_id') or None
        donor = Donor.objects.filter(id=donor_id).first()
        donation_form = DonationForm(request.POST, instance=donation)
        if donation_form.is_valid():
            donation = donation_form.save(commit=False)
            donation.donor = donor
            donation.save()
            if donation_id:
                messages.success(request, 'Donation Updated Successfully')
                return redirect('dashboard:donations')
            else:
                messages.success(request, 'Donation Saved Successfully')
                return redirect('dashboard:donations')
        else:
            for k, v in donation_form.errors.items():
                messages.info(request, f'{k}: {v}')
                return redirect('dashboard:donations')


class SearchDonationView(PermissionRequiredMixin, View):
    '''Class for searching Donation'''
    permission_required = ['dashboard.view_donation']

    template = 'dashboard/donations.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        donations = Donation.objects.filter(
            Q(donor__blood_type__icontains=query) |
            Q(donation_id__icontains=query) |
            Q(donor__email__icontains=query) |
            Q(donor__fullname__icontains=query)
        ).order_by('-created_at')
        context = {
            'donations': donations,
        }
        return render(request, self.template, context)


class DeleteDonationView(PermissionRequiredMixin, View):
    '''Class for deleting Donations'''
    permission_required = ['dashboard.delete_donation']

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:donations')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donation_id = request.POST.get('donation_id')
        donation = Donation.objects.filter(id=donation_id).first()
        if donation:
            donation.delete()
            messages.success(request, 'Donation Deleted successfully')
        else:
            messages.info(request, 'Donation Does Not Exist')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/dashboard/views/donors.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from core.utils.constants import BloodType as BT
from core.utils.constants import Titles as T
from core.utils.decorators import MustLogin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View
from dashboard.models import Donor
from dashboard.forms import DonorForm


class DonorsListView(PermissionRequiredMixin, View):

    '''Class for showing the list of Donors'''
    permission_required = ['dashboard.view_department']

    template = 'dashboard/donors.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        donors = Donor.objects.all().order_by('-created_at')
        blood_types = BT.__members__.keys()
        titles = T.__members__.keys()
        context = {
            'donors': donors,
            'blood_types': blood_types,
            'titles': titles,
        }
        return render(request, self.template, context)


class CreateUpdateDonorView(PermissionRequiredMixin, View):
    '''Class for creating and updating a donor'''
    permission_required = ['dashboard.add_donor', 'dashboard.change_donor']

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:donors')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donor_id = request.POST.get('donor_id')
        donor = Donor.objects.filter(id=donor_id).first()
        donor_form = DonorForm(request.POST, instance=donor)

        # donor exists - update
        if donor:
            if donor_form.is_valid():
                item = donor_form.save(commit=False)
                item.created_by = request.user
                item.save()
                messages.success(request, 'Donor updated successfully')
            else:
                for k, v in donor_form.errors.items():
                    print(k, v)
                    messages.info(request, f'{k}: {v}')
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:  # create new donor
            donor_form = DonorForm(request.POST)
            if donor_form.is_valid():
                item = donor_form.save(commit=False)
                if not item.created_by:
                    item.created_by = request.user
                item.save()
                messages.success(request, 'Donor created successfully')
            else:
                for k, v in donor_form.errors.items():
                    print(k, v)
                    messages.info(request, f'{k}: {v}')
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class SearchDonorView(PermissionRequiredMixin, View):
    '''Class for searching donor'''
    permission_required = ['dashboard.view_donor']

    template = 'dashboard/donors.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        donors = Donor.objects.filter(
            Q(blood_type__icontains=query) |
            Q(address__icontains=query) |
            Q(phone__icontains=query) |
            Q(fullname__icontains=query) |
            Q(title__icontains=query) |
            Q(ocupation__icontains=query) |
            Q(medical_condition__icontains=query)
        ).order_by('-created_at')
        context = {
            'donors': donors,
        }
        return render(request, self.template, context)


class DeleteDonorView(PermissionRequiredMixin, View):
    '''Class for deleting Donors'''
    permission_required = ['dashboard.delete_donor']

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:donors')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donor_id = request.POST.get('donor_id')
        donor = Donor.objects.filter(id=donor_id).first()
        if donor:
            donor.delete()
            messages.success(request, 'Donor deleted successfully')
        else:
            messages.info(request, 'Donor does not exist')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/dashboard/templates/dashboard/details/details_blood_request.html
{% extends "base/base.html" %}

{% block title %} Blood Requests | {{blood_request.blood_request_id}} {% endblock %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item"><a href="#">Blood Requests</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{blood_request.blood_request_id}}</li>
            </ol>
        </nav>
        <h2 class="h4">{{blood_request.blood_request_id}}</h2>
        <p class="mb-0">Details for the blood request {{blood_request.blood_request_id}}</p>
    </div>

    {% if perms.accounts.delete_user %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group ms-2 ms-lg-3">
            <form action="{% url 'dashboard:delete_blood_request' %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="blood_request_id" value="{{blood_request.blood_request_id}}">
                <button type="submit" class="btn btn-sm btn-outline-gray-600"><span
                        class="fas fa-trash-alt me-2"></span>Delete Request</button>
            </form>
        </div>
    </div>
    {% endif %}

</div>

<div class="card card-body border-0 shadow table-wrapper table-responsive mb-4">
    <div class="row">

        <div class="col-4 mb-3">
            <b>Request ID</b>
            <p class="text-primary">{{blood_request.blood_request_id}}</p>
        </div>

        <div class="col-4 mb-3">
            <b>Request Form</b> <br>
            <img src="{% if blood_request.request_form %} {{blood_request.request_form.url}} {% else %} {% static 'assets/img/icons/form.png' %} {% endif %}"
                style="height: 80px; width: 80px; border-radius: 50%;" alt="">
            <button type="button" class="btn btn-sm mb-3" data-bs-toggle="modal" data-bs-target="#modal-default"><span
                    class="fas fa-eye"></span></button>
        </div>

        <div class="col-4 mb-3">
            <b>Patient</b>
            <p class="text-primary">{{blood_request.patient_profile.user.fullname}}</p>
        </div>

        <div class="col-4 mb-3">
            <b>Blood Type</b>
            <p class="text-primary">{{blood_request.patient_profile.blood_type}}</p>
        </div>

        <div class="col-4 mb-3">
            <b>Status</b>
            <p class="text-primary"> <span class="badge p-2"
                    style="background-color: {{blood_request.get_status_color}};">{{blood_request.status}}</span> </p>
        </div>

        <div class="col-4 mb-3">
            <b>Quantity</b>
            <p class="text-primary">{{blood_request.quantity}}</p>
        </div>

        <div class="col-4 mb-3">
            <b>Date Requested</b>
            <p class="text-primary">{{blood_request.date_requested}}</p>
        </div>

        <div class="col-4 mb-3">
            <b>Date Approved/Rejected</b>
            <p class="text-primary">{{blood_request.date_approve_rejected}}</p>
        </div>
    </div>
</div>

{% if perms.dashboard.change_request_status %}
<div class="card card-body border-0 shadow table-wrapper table-responsive">
    <div class="row">
        <div class="col-6">
            <h2 class="h4">Status</h2>
            <form action="{% url 'dashboard:change_request_status' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="request_id" value="{{blood_request.id}}">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="request_status" value="PENDING"
                        id="request_status1" {% if blood_request.status == 'PENDING' %} checked {% endif %}>
                    <label class="form-check-label" for="request_status1">
                        PENDING
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="request_status" value="APPROVED"
                        id="request_status2" {% if blood_request.status == 'APPROVED' %} checked {% endif %}>
                    <label class="form-check-label" for="request_status2">
                        APPROVED
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="request_status" value="REJECTED"
                        id="request_status2" {% if blood_request.status == 'REJECTED' %} checked {% endif %}>
                    <label class="form-check-label" for="request_status2">
                        REJECTED
                    </label>
                </div>
                <div class="">
                    <input type="submit" class="btn btn-sm btn-primary" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}

<!-- Modal Content -->
<div class="modal fade" id="modal-default" tabindex="-1" role="dialog" aria-labelledby="modal-default"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="card-title">
                    <h2 class="h6 modal-title">{{blood_request.blood_request_id}}</h2>
                </div>
                <img src="{% if blood_request.request_form %} {{blood_request.request_form.url}} {% else %} {% static 'assets/img/icons/form.png' %} {% endif %} "
                    alt="" class="card-img-top" style="width: 100%; height:auto;">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- End of Modal Content -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/dashboard/templates/dashboard/details/details_user_permissions.html
{% extends "base/base.html" %}

{% block title %} Setup | User Permissions {% endblock %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item"><a href="#">Setup</a></li>
                <li class="breadcrumb-item active" aria-current="page">User</li>
            </ol>
        </nav>
        <h2 class="h4">{{user.fullname|upper}}</h2>
        <p class="mb-0">Groups and Permissions for {{user.fullname}}</p>
    </div>

    {% if perms.accounts.delete_user %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group ms-2 ms-lg-3">
            <form action="{% url 'dashboard:delete_user' %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{user.id}}">
                <button type="submit" class="btn btn-sm btn-outline-gray-600"><span
                        class="fas fa-trash-alt me-2"></span>Delete User</button>
            </form>
        </div>
    </div>
    {% endif %}

</div>

<div class="card card-body border-0 shadow table-wrapper table-responsive mb-4">
    <div class="row">
        <div class="col-4 mb-3">
            <b>User ID</b>
            <p class="text-primary">{{user.id}}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Fullname</b>
            <p class="text-primary">{{user.get_fullname}}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Account Type</b>
            <p class="text-primary">{% if user.is_patient %} Patient {% elif user.is_staff %} Staff
                {% elif user.is_superuser %}
                Superuser {% else %} None {% endif %}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Total Groups</b>
            <p class="text-primary">{{user.groups.count}}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Is Staff</b>
            <p class="text-primary">{{user.is_staff}}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Is Superuser</b>
            <p class="text-primary">{{user.is_superuser}}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Is Patient</b>
            <p class="text-primary">{{user.is_patient}}</p>
        </div>
        <div class="col-4 mb-3">
            <b>Total Permissions</b>
            <p class="text-primary">{{user.user_permissions.count}}</p>
        </div>
    </div>
</div>

<div class="card card-body border-0 shadow table-wrapper table-responsive">
    <div class="row">
        <div class="col-6">
            <h2 class="h4">Groups</h2>
        </div>
        <div class="col-6">
            <h2 class="h4">Permissions</h2>
        </div>
        <div class="col-6">
            <form action="{% url 'dashboard:add_user_to_group' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{user.id}}">
                {% for group in groups %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="{{group.id}}" name="groups"
                        id="group_id_{{group.id}}" {% if group in saved_groups %} checked {% endif %}>
                    <label class="form-check-label" for="perm_id_{{group.id}}">
                        {{group.name}}
                    </label>
                </div>
                {% endfor %}
                <input type="hidden" name="group_id" value="{{group.id}}">

                {% if perms.accounts.add_user_to_group %}
                <button type="submit" class="mt-3 btn btn-sm btn-primary"><i class="bi bi-cloud-upload"
                        style="margin-right: 10px;"></i>Save Groups</button>
                {% endif %}

            </form>
        </div>
        <div class="col-6">
            <form action="{% url 'dashboard:add_perms_to_user' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{user.id}}">
                {% for permission in permissions %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="{{permission.id}}" name="permissions"
                        id="perm_id_{{permission.id}}" {% if permission in saved_permissions %} checked {% endif %}>
                    <label class="form-check-label" for="perm_id_{{permission.id}}">
                        {{permission.name}}
                    </label>
                </div>
                {% endfor %}
                <input type="hidden" name="group_id" value="{{group.id}}">

                {% if perms.accounts.add_permission_to_user %}
                <button type="submit" class="mt-3 btn btn-sm btn-primary"><i class="bi bi-cloud-upload"
                        style="margin-right: 10px; border-style: none;"></i>Save Permissions</button>
                {% endif %}

            </form>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}