core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
]


# use Django's local server to serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

# for patients
urlpatterns += [
    path('patients/', views.PatientsListView.as_view(), name='patients'),
    path('create-update-patient/',
         views.CreateUpdatePatientView.as_view(), name='create_update_patient'),
    path('search-patient/', views.SearchPatientView.as_view(), name='search_patient'),  # noqa
    path('delete-patient/', views.DeletePatientView.as_view(), name='delete_patient'),  # noqa
]

# for donors
urlpatterns += [
    path('donors/', views.DonorsListView.as_view(), name='donors'),
    path('create-update-donor/', views.CreateUpdateDonorView.as_view(),
         name='create_update_donor'),
    path('search-donor/', views.SearchDonorView.as_view(), name='search_donor'),
    path('delete-donor/', views.DeleteDonorView.as_view(), name='delete_donor'),
]

# for donations
urlpatterns += [
    path('donations/', views.DonationsListView.as_view(), name='donations'),
    path('create-update-donation/', views.CreateUpdateDonationView.as_view(), name='create_update_donation'),  # noqa
    path('search-donation/', views.SearchDonationView.as_view(), name='search_donation'),  # noqa
    path('delete-donation/', views.DeleteDonationView.as_view(), name='delete_donation'),  # noqa
]

# for blood requests
urlpatterns += [
    path('blood-requests/', views.BloodRequestsListView.as_view(), name='blood_requests'),  # noqa
    path('create-update-blood-request/', views.CreateUpdateBloodRequestView.as_view(), name='create_update_blood_request'),  # noqa
    path('blood-request-detail/', views.BloodRequestDetailsView.as_view(), name='blood_request_detail'),  # noqa
    path('search-blood-request/', views.SearchBloodRequestView.as_view(), name='search_blood_request'),  # noqa
    path('change-request-status/', views.ChangeRequestStatusView.as_view(), name='change_request_status'),  # noqa
    path('delete-blood-request/', views.DeleteBloodRequestView.as_view(), name='delete_blood_request'),  # noqa
]


# Users
urlpatterns += [
    path("users/", views.UsersListView.as_view(), name="users"),
    path("create-update-user/", views.CreateUpdateUserView.as_view(), name="create_update_user"),  # noqa
    path("search-user/", views.SearchUserView.as_view(), name="search_user"),  # noqa
    path("delete-user/", views.DeleteUserView.as_view(), name="delete_user"),  # noqa
    path("add-user-to-group/", views.AddUserToGroupsView.as_view(), name="add_user_to_group"),  # noqa
    path("add-perms-to-user/", views.AddPermsToUserView.as_view(), name="add_perms_to_user"),  # noqa
]

# Groups
urlpatterns += [
    path("groups/", views.GroupsListView.as_view(), name="groups"),
    path("create-update-group/", views.CreateUpdateGroupView.as_view(), name="create_update_group"),  # noqa
    path("search-group/", views.SearchGroupView.as_view(), name="search_group"),  # noqa
    path("delete-group/", views.DeleteGroupView.as_view(), name="delete_group"),  # noqa
    path('add-perms/', views.AddPermissionsToGroupView.as_view(), name='add_perms'),  # noqa
]


# profile urls
urlpatterns += [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update-profile/', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
]

core/dashboard/forms.py
from django import forms
from accounts.models import User
from dashboard.models import Donor, PatientProfile, Donation, BloodRequest


class UserForm(forms.ModelForm):
    '''Form for creating a new user'''
    class Meta:
        model = User
        fields = ['email', 'fullname', 'phone', 'gender', 'profile_image', ]


class PatientProfileForm(forms.ModelForm):
    '''Form for creating a new user profile'''
    class Meta:
        model = PatientProfile
        exclude = ['created_at', 'user', ]


class DonorForm(forms.ModelForm):
    '''Form for creating a new donor'''
    class Meta:
        model = Donor
        exclude = ['created_at', 'created_by', ]


class DonationForm(forms.ModelForm):
    '''Form for creating a new donation'''
    class Meta:
        model = Donation
        fields = ['date_time_donated', 'quantity', ]


class BloodRequestForm(forms.ModelForm):
    '''Form for creating a new blood request'''
    class Meta:
        model = BloodRequest
        fields = ['quantity', ]

core/dashboard/views/dashboard.py
import datetime
from datetime import timedelta, timezone
from django.utils import timezone as tz
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View
from dashboard.models import Donation, Donor, PatientProfile, BloodRequest
from django.db.models import Count, Sum, F, FloatField
from core.utils.decorators import MustLogin
from django.utils.decorators import method_decorator


class DashboardView(View):
    '''CBV for rendering the dashboard page'''

    template = 'dashboard/dashboard.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        # expired bloods
        expired_blood_count = Donation.objects.filter(
            date_time_donated__lte=tz.now()-timedelta(days=40)).count()
        # bloods expiring in a week or less
        expiring_blood_count = Donation.objects.filter(date_time_donated__gt=tz.now(
        )-timedelta(days=40), date_time_donated__lte=tz.now()+timedelta(days=7)).count()
        # messages
        message = f'{expired_blood_count} quantum of blood has expired | {expiring_blood_count} quantum of blood will expire in a week or less'  # noqa
        blood_types = Donation.objects.values_list('donor__blood_type', flat=True).distinct()  # noqa
        blood_type_counts = Donation.objects.values('donor__blood_type').annotate(count=Count('donor__blood_type'))  # noqa

        # get the total quantity of each blood type in the Donation model
        blood_type_totals = Donation.objects.values(
            'donor__blood_type').annotate(total_quantity=Sum('quantity'))

        # get the total quantity of each blood type requested in the BloodRequest model
        blood_type_requests = BloodRequest.objects.filter(status__in=['PENDING', 'REJECTED']).values(
            'patient_profile__blood_type').annotate(requested_quantity=Sum('quantity'))

        # combine the above queries to get the final result
        blood_type_info = []
        for blood_type in set(blood_type_totals.values_list('donor__blood_type', flat=True)):

            total_quantity = blood_type_totals.filter(
                donor__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type).aggregate(Sum('quantity'))['quantity__sum']

            approve_requested_quantity = blood_type_requests.filter(
                patient_profile__blood_type=blood_type, status='APPROVED').aggregate(Sum('quantity'))['quantity__sum']

            available_quantity = float(
                total_quantity) - float(approve_requested_quantity or 0)

            blood_type_info.append({
                'blood_type': blood_type,
                'total_quantity': str(total_quantity or 0),
                'requested_quantity': str(requested_quantity or 0),
                'approve_requested_quantity': str(approve_requested_quantity or 0),
                'available_quantity': str(available_quantity)
            })

        # only display messages blood expiration message to staff and superusers
        if request.user.is_staff or request.user.is_superuser:
            messages.info(request, message)
        request_history = BloodRequest.objects.filter(
            patient_profile__user=request.user).order_by('-blood_request_id')

        context = {
            'blood_types': blood_types,
            'blood_type_counts': blood_type_counts,
            'blood_type_info': blood_type_info,
            'request_history': request_history,
        }

        return render(request, self.template, context)

core/dashboard/views/donations.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from core.utils.decorators import MustLogin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View
from dashboard.models import Donation, Donor
from dashboard.forms import DonationForm


class DonationsListView(PermissionRequiredMixin, View):
    '''Class for showing the list of Donations'''
    permission_required = ['dashboard.view_donation']

    template = 'dashboard/donations.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        donations = Donation.objects.all().order_by('-created_at')
        context = {
            'donations': donations,
        }
        return render(request, self.template, context)


class CreateUpdateDonationView(PermissionRequiredMixin, View):
    '''Class for creating and updating donations'''
    permission_required = ['dashboard.add_donation']
    template = 'dashboard/form-renderers/create_update_donation.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        donation_id = request.GET.get('donation_id') or None
        donation = Donation.objects.filter(id=donation_id).first()
        donors = Donor.objects.all().order_by('-id')
        context = {
            'donation': donation,
            'donors': donors,
        }
        return render(request, self.template, context)

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donation_id = request.POST.get('donation_id') or None
        donation = Donation.objects.filter(id=donation_id).first()
        donor_id = request.POST.get('donor_id') or None
        donor = Donor.objects.filter(id=donor_id).first()
        donation_form = DonationForm(request.POST, instance=donation)
        if donation_form.is_valid():
            donation = donation_form.save(commit=False)
            donation.donor = donor
            donation.save()
            if donation_id:
                messages.success(request, 'Donation Updated Successfully')
                return redirect('dashboard:donations')
            else:
                messages.success(request, 'Donation Saved Successfully')
                return redirect('dashboard:donations')
        else:
            for k, v in donation_form.errors.items():
                messages.info(request, f'{k}: {v}')
                return redirect('dashboard:donations')


class SearchDonationView(PermissionRequiredMixin, View):
    '''Class for searching Donation'''
    permission_required = ['dashboard.view_donation']

    template = 'dashboard/donations.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        donations = Donation.objects.filter(
            Q(donor__blood_type__icontains=query) |
            Q(donation_id__icontains=query) |
            Q(donor__email__icontains=query) |
            Q(donor__fullname__icontains=query)
        ).order_by('-created_at')
        context = {
            'donations': donations,
        }
        return render(request, self.template, context)


class DeleteDonationView(PermissionRequiredMixin, View):
    '''Class for deleting Donations'''
    permission_required = ['dashboard.delete_donation']

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:donations')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donation_id = request.POST.get('donation_id')
        donation = Donation.objects.filter(id=donation_id).first()
        if donation:
            donation.delete()
            messages.success(request, 'Donation Deleted successfully')
        else:
            messages.info(request, 'Donation Does Not Exist')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/dashboard/views/donors.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from core.utils.constants import BloodType as BT
from core.utils.constants import Titles as T
from core.utils.decorators import MustLogin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View
from dashboard.models import Donor
from dashboard.forms import DonorForm


class DonorsListView(PermissionRequiredMixin, View):

    '''Class for showing the list of Donors'''
    permission_required = ['dashboard.view_department']

    template = 'dashboard/donors.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        donors = Donor.objects.all().order_by('-created_at')
        blood_types = BT.__members__.keys()
        titles = T.__members__.keys()
        context = {
            'donors': donors,
            'blood_types': blood_types,
            'titles': titles,
        }
        return render(request, self.template, context)


class CreateUpdateDonorView(PermissionRequiredMixin, View):
    '''Class for creating and updating a donor'''
    permission_required = ['dashboard.add_donor', 'dashboard.change_donor']

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:donors')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donor_id = request.POST.get('donor_id')
        donor = Donor.objects.filter(id=donor_id).first()
        donor_form = DonorForm(request.POST, instance=donor)

        # donor exists - update
        if donor:
            if donor_form.is_valid():
                item = donor_form.save(commit=False)
                item.created_by = request.user
                item.save()
                messages.success(request, 'Donor updated successfully')
            else:
                for k, v in donor_form.errors.items():
                    print(k, v)
                    messages.info(request, f'{k}: {v}')
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:  # create new donor
            donor_form = DonorForm(request.POST)
            if donor_form.is_valid():
                item = donor_form.save(commit=False)
                if not item.created_by:
                    item.created_by = request.user
                item.save()
                messages.success(request, 'Donor created successfully')
            else:
                for k, v in donor_form.errors.items():
                    print(k, v)
                    messages.info(request, f'{k}: {v}')
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class SearchDonorView(PermissionRequiredMixin, View):
    '''Class for searching donor'''
    permission_required = ['dashboard.view_donor']

    template = 'dashboard/donors.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        donors = Donor.objects.filter(
            Q(blood_type__icontains=query) |
            Q(address__icontains=query) |
            Q(phone__icontains=query) |
            Q(fullname__icontains=query) |
            Q(title__icontains=query) |
            Q(ocupation__icontains=query) |
            Q(medical_condition__icontains=query)
        ).order_by('-created_at')
        context = {
            'donors': donors,
        }
        return render(request, self.template, context)


class DeleteDonorView(PermissionRequiredMixin, View):
    '''Class for deleting Donors'''
    permission_required = ['dashboard.delete_donor']

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('dashboard:donors')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        donor_id = request.POST.get('donor_id')
        donor = Donor.objects.filter(id=donor_id).first()
        if donor:
            donor.delete()
            messages.success(request, 'Donor deleted successfully')
        else:
            messages.info(request, 'Donor does not exist')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/dashboard/templates/dashboard/forms/form_donation.html
<form id="donation-form" action="{% url 'dashboard:create_update_donation' %}" method="POST"
    style="border: 2px solid blue; padding: 30px 50px;">
    {% csrf_token %}
    <input type="hidden" name="donation_id" value="{{donation.donation_id}}">

    <div class="mb-3">
        <label for="donation-donor_id" class="form-label">Donor</label>
        <select class="form-select" name="donor_id" id="donation-donor_id" required>
            <option value="">Choose...</option>
            {% for donor in donors %}
            <option value="{{donor.id}}" {% if donor.id == donation.donor.id %} selected {% endif %}>{{donor.fullname}}
            </option>
            {% endfor %}

        </select>
    </div>

    <div class="mb-3">
        <label for="donation-date_time_created" class="form-label">Date of Donation</label>
        <input type="datetime-local" name="date_time_donated" value="{{ donation.date_time_donated|date:'Y-m-d\TH:i' }}"
            class="form-control" id="donation-date_time_donated">

    </div>

    <div class="mb-3">
        <label for="donation-quantity" class="form-label">Quantity</label>
        <input type="number" name="quantity" value="{{donation.quantity}}" class="form-control" id="donation-quantity"
            step="0.1" min="0" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

core/dashboard/templates/dashboard/forms/form_donor.html
<form action="{% url 'dashboard:create_update_donor' %}" style="padding: 30px 30px;" method="POST"
    enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="equipment_id" value="{{equipment.id}}">
    <fieldset>
        <legend>Enter Details to Create Donor</legend>
        <!-- main form content -->
        <div class="mb-4">
            <label for="fullname">Fullname*</label>
            <input type="text" class="form-control" name="fullname" value="{{donor.fullname}}"
                aria-describedby="fullnameHelp" required>
        </div>
        <div class="mb-4">
            <label for="email">Email*</label>
            <input type="email" class="form-control" name="email" value="{{donor.email}}" aria-describedby="emailHelp">
        </div>
        <div class="mb-4">
            <label for="title">Title*</label>
            <select name="title" class="form-control">
                {% for title in titles %}
                <option value="{{title}}" {% if donor.title == title %} selected {% endif %}>
                    {{title}}
                </option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-4">
            <label for="blood_type">Blood Type*</label>
            <select name="blood_type" class="form-control">

                {% comment %}
                {% for blood in blood_types %}
                <option value="{{blood}}" {% if donor.blood_type == blood %} selected {% endif %}>
                    {{blood}}
                </option>
                {% endfor %}
                {% endcomment %}

                <option value="">Choose...</option>
                <option value="A_POSITIVE" {% if donor.blood_type == 'A_POSITIVE' %} selected {% endif %}>A+</option>
                <option value="A_NEGATIVE" {% if donor.blood_type == 'A_NEGATIVE' %} selected {% endif %}>A-</option>
                <option value="B_POSITIVE" {% if donor.blood_type == 'B_POSITIVE' %} selected {% endif %}>B+</option>
                <option value="B_NEGATIVE" {% if donor.blood_type == 'B_NEGATIVE' %} selected {% endif %}>B-</option>
                <option value="AB_POSITIVE" {% if donor.blood_type == 'AB_POSITIVE' %} selected {% endif %}>AB+
                </option>
                <option value="AB_NEGATIVE" {% if donor.blood_type == 'AB_NEGATIVE' %} selected {% endif %}>AB-
                </option>
                <option value="O_POSITIVE" {% if donor.blood_type == 'O_POSITIVE' %} selected {% endif %}>O+</option>
                <option value="O_NEGATIVE" {% if donor.blood_type == 'O_NEGATIVE' %} selected {% endif %}>O-</option>
            </select>
        </div>
        <div class="mb-4">
            <label for="dob">Date of Birth*</label>
            <input type="date" class="form-control" name="dob" value="{{donor.dob}}" aria-describedby="dobHelp"
                required>
        </div>
        <div class="mb-4">
            <label for="ocupation">Ocupation*</label>
            <input type="text" class="form-control" name="ocupation" value="{{donor.ocupation}}"
                aria-describedby="ocupationHelp" required>
        </div>
        <div class="mb-4">
            <label for="address">Address*</label>
            <input type="text" class="form-control" name="address" value="{{donor.address}}"
                aria-describedby="addressHelp" required>
        </div>
        <div class="mb-4">
            <label for="phone">Phone*</label>
            <input type="text" class="form-control" name="phone" value="{{donor.phone}}" aria-describedby="phoneHelp"
                required>
        </div>

        <div class="mb-4">
            <label for="gender">Gender</label>
            <select name="gender" class="form-control">
                <option selected> Gender </option>
                <option value="Male" {% if donor.gender == "Male" %} selected {% endif %}>
                    Male
                </option>
                <option value="Female" {% if donor.gender == "Female" %} selected {% endif %}>
                    Female
                </option>
            </select>
        </div>
        <div class="mb-4">
            <label for="id_type">ID Type</label>
            <select name="id_type" class="form-control">
                <option selected> ID Type </option>
                <option value="GH Card" {% if donor.id_type == "GH Card" %} selected {% endif %}>
                    GH Card
                </option>
                <option value="Voter ID" {% if donor.id_type == "Voter ID" %} selected {% endif %}>
                    Voter ID
                </option>
                <option value="NHIS Card" {% if donor.id_type == "NHIS Card" %} selected {% endif %}>
                    NHIS Card
                </option>
            </select>
        </div>
        <div class="mb-4">
            <label for="id_number">ID Number*</label>
            <input type="text" class="form-control" name="id_number" value="{{donor.id_number}}"
                aria-describedby="id_numberHelp" required>
        </div>
        <div class="mb-4">
            <label for="medical_condition">Medical Condition*</label>
            <textarea name="medical_condition" cols="30" rows="5"
                class="form-control">{{donor.medical_condition}}</textarea>
        </div>

        <div class="mb-4">
            <input type="submit" class="btn btn-sm btn-block btn-primary" value="Submit">
        </div>
    </fieldset>
</form>

core/dashboard/templates/dashboard/forms/form_group.html
<form action="{% url 'dashboard:create_update_group' %}" style="border: 2px solid blue; padding: 30px 50px;"
    method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="group_id" value="{{group.id}}">
    <fieldset>
        <legend>Group Creation/Updation Form</legend>
        <!-- main form content -->
        <div class="mb-4">
            <label for="name">Group Name*</label>
            <input type="text" class="form-control" name="name" value="{{group.name}}" aria-describedby="nameHelp"
                required>
        </div>
        <div class="mb-4">
            <input type="submit" class="btn btn-sm btn-block btn-primary" value="Submit">
        </div>
    </fieldset>
</form>

core/dashboard/templates/dashboard/forms/form_patient.html
<form id="signup-form" action="{% url 'dashboard:create_update_patient' %}" method="POST" enctype="multipart/form-data"
    style="border: 2px solid blue; padding: 30px 50px;">
    {% csrf_token %}
    <input type="hidden" name="user_id" value="{{patient.user.id}}">
    <input type="hidden" name="patient_id" value="{{patient.id}}">
    <div class="mb-3">
        <label for="signup-fullname" class="form-label">Full Name</label>
        <input type="text" name="fullname" value="{{patient.user.fullname}}" class="form-control" id="signup-fullname"
            required>
    </div>
    <div class="mb-3">
        <label for="signup-email" class="form-label">Email</label>
        <input type="email" name="email" value="{{patient.user.email}}" class="form-control" id="signup-email" required>
    </div>
    <div class="mb-3">
        <label for="signup-phone" class="form-label">Phone</label>
        <input type="tel" name="phone" value="{{patient.user.phone}}" class="form-control" id="signup-phone" required>
    </div>
    <div class="mb-3">
        <label for="signup-gender" class="form-label">Gender</label>
        <select class="form-select" name="gender" id="signup-gender" required>
            <option value="">Choose...</option>
            <option value="Male" {% if patient.user.gender == 'Male' %} selected {% endif %}>Male</option>
            <option value="Female" {% if patient.user.gender == 'Female' %} selected {% endif %}>Female
            </option>
        </select>
    </div>
    <div class="mb-3">
        <label for="signup-profile_image" class="form-label">Profile
            Image</label>
        <input type="file" name="profile_image" class="form-control" id="signup-profile_image" accept="image/*">
    </div>
    <div class="mb-3">
        <label for="signup-blood_type" class="form-label">Blood
            Type</label>
        <select class="form-select" name="blood_type" id="signup-blood_type" required>
            <option value="">Choose...</option>
            <option value="A_POSITIVE" {% if patient.blood_type == 'A_POSITIVE' %} selected {% endif %}>A+</option>
            <option value="A_NEGATIVE" {% if patient.blood_type == 'A_NEGATIVE' %} selected {% endif %}>A-</option>
            <option value="B_POSITIVE" {% if patient.blood_type == 'B_POSITIVE' %} selected {% endif %}>B+</option>
            <option value="B_NEGATIVE" {% if patient.blood_type == 'B_NEGATIVE' %} selected {% endif %}>B-</option>
            <option value="AB_POSITIVE" {% if patient.blood_type == 'AB_POSITIVE' %} selected {% endif %}>AB+</option>
            <option value="AB_NEGATIVE" {% if patient.blood_type == 'AB_NEGATIVE' %} selected {% endif %}>AB-</option>
            <option value="O_POSITIVE" {% if patient.blood_type == 'O_POSITIVE' %} selected {% endif %}>O+</option>
            <option value="O_NEGATIVE" {% if patient.blood_type == 'O_NEGATIVE' %} selected {% endif %}>O-</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="signup-dob" class="form-label">Date of
            Birth</label>
        <input type="date" name="dob" value="{{patient.dob|date:'Y-m-d'}}" class="form-control" id="signup-dob"
            required>
    </div>
    <div class="mb-3">
        <label for="signup-address" class="form-label">Address</label>
        <textarea class="form-control" name="address" id="signup-address" rows="3"
            required>{{patient.address}}</textarea>
    </div>
    <hr>
    <div class="mb-3">
        <label for="signup-password" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="signup-password" {% if not patient %} required
            {% endif %}>
    </div>
    <div class="mb-3">
        <label for="signup-password2" class="form-label">Confirm Password</label>
        <input type="password" name="password2" class="form-control" id="signup-password2" {% if not patient %} required
            {% endif %}>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

core/dashboard/templates/dashboard/forms/form_request.html
<form id="donation-form" action="{% url 'dashboard:create_update_blood_request' %}" method="POST"
    style="border: 2px solid blue; padding: 30px 50px;" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="request_id" value="{{blood_request.id}}">

    <div class="mb-3">
        <label for="request-quantity" class="form-label">Quantity</label>
        <input type="number" name="quantity" value="{{blood_request.quantity}}" class="form-control"
            id="request-quantity" step="0.1" min="0" required>
    </div>
    <div class="mb-3">
        <label for="request-request_form" class="form-label">Blood Request Form</label>
        <input type="file" name="request_form" class="form-control" id="request-quantity" accept="image/*" required>
    </div>
    <button type="submit" class="btn btn-primary">Make Request</button>
</form>